[package]
name = "airline_seating"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cursive = { version = "0.20.0", features = ["crossterm-backend"], default-features = false}
cursive_buffered_backend = "0.6.1"
